spring:
  application:
    name: game-backend
  jackson:
    default-property-inclusion: non_null

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update  # dev update, prod validate/none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

logging:
  level:
    org:
      springframework: INFO

jwt:
  secret: ${JWT_SECRET}
  expiration: 604800000 # 7일. 게임도중에 JWT 만료되는 것 방지. 리프레쉬 토큰 도입안하고 기간늘려버림.

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

---
